schema_version = "1.0.0"

id = "import_png_palette"
name = "Import PNG Palette"
version = "1.0.1"
tagline = "Import PNG images as color palettes for Blender"
maintainer = "Ruuubick"
type = "add-on"

blender_version_min = "4.2.0"

license = ["SPDX:GPL-3.0-or-later"]

website = "https://lospec.com/palette-list"
copyright = [
    "2025 Thomas Bonnay",
]

tags = ["Import-Export", "Paint"]

[description]
summary = "Lets you import color palettes directly from PNG images, perfect for Lospec palettes and other pixel-art color sets"
